name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Change this to run on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Specify the Python version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Optional: Lint the code with flake8
      - name: Lint code with flake8
        run: |
          flake8 .  # Lint the whole repository (you can change the directory if needed)

      # Run tests using pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Customize pytest flags if necessary
